spring.application.name=app

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/coworking_hub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:coworking}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:coworking123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC
spring.jpa.open-in-view=false
spring.docker.compose.enabled=false

app.jwt.secret=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
app.jwt.access-token-expiration-seconds=3600

app.upload.base-dir=uploads
app.upload.public-prefix=/uploads
